client_config_backend: settings
client_config:
    client_id: 928685036169-em2od9at7tjgh4kbqk6v53r48n6slhvi.apps.googleusercontent.com
    client_secret: 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

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive.file
    - https://www.googleapis.com/auth/drive.install
